[home]
titulo = "Painel Desafio Target"
subtitulo = "De uma Conferida no Menu ao Lado"
introducao_painel = "O Painel está dividido em paginas por Menu, onde cada aba representa uma tarefa atribuida no desafio."

GitHub = "Acesse o Repositório no GitHub: https://github.com/jvras58/Desafio_Target_Sistemas"

[tarefa_1]
titulo = "Cálculo da Soma"
descricao = "A primeira tarefa consiste em criar um código que calcule a soma de todos os números pares de 0 a 1000."

[tarefa_2]
titulo = "Verificação de Número na Sequência de Fibonacci"
descricao = "A segunda tarefa consiste em criar um codigo que verifica se um número é parte da sequência de Fibonacci."

[tarefa_3]
titulo = "Análise de Faturamento Diário"
descricao = "A terceira tarefa consiste em criar um código que analise o faturamento diário de uma empresa a partir do json carregado."

[tarefa_4]
titulo = "Cálculo da Representação Percentual por Estado"
descricao = "A quarta tarefa consiste em criar um código que analise o faturamento diário de uma empresa a partir do json carregado."

[tarefa_5]
titulo = "Inversão de String"
descricao = "A quinta tarefa consiste criar um algoritmo que reverta a string fornecida sem usar funções prontas."
